# General Accessibility Audit Configuration

timeout: 90000
runners:
  - htmlcs
  - axe
waitUntil: 'networkidle2'
chromeLaunchConfig:
  headless: false
  args:
    - '--no-sandbox'
    - '--disable-setuid-sandbox'
    - '--lang=ca-ES'
  slowMo: 50
